server:
  port: 8080

spring:
  application:
    name: metrify-demo

metrify:
  enabled: true
  prefix: demo
  validation:
    mode: WARN
  grafana:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrify
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
